name: Test connectivity check servers

on:
  schedule:
    - cron: '5 8 * * 6'
  workflow_dispatch:

jobs:
  test-the-servers:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Servers test: Python 3.8'
            python: '3.8'
          - name: 'Servers test: Python 3.9'
            python: '3.9'
          - name: 'Servers test: Python 3.10'
            python: '3.10'
          - name: 'Servers test: Python 3.11'
            python: '3.11'
          - name: 'Servers test: Python 3.12'
            python: '3.12'
          - name: 'Servers test: Python latest 3.x'
            python: '3.x'

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Display Python version
        run: python --version
      - name: Install tox
        run: python -m pip install tox
      - name: tox
        run: python -m tox -e serverstest
