name: Test connectivity check servers

on:
  schedule:
    - cron: "5 8 * * 6"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

    name: Test servers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tox
        run: python -m pip install tox
      - name: tox
        run: python -m tox -e testservers
